### ISSUE TITLE
Can't download because `This repository is over its data quota`

### ISSUE THREAD

**Issue by Tienipia** [Shining3D/EinScan-SDK#1]
According to `Git-LFS` official documents, there is a bandwidth limit per account
For details : https://help.github.com/articles/about-storage-and-bandwidth-usage/

You're repository is now over above bandwidth(1GB/month) so I can't pull the resource, which have git-lfs pointer (like [`SDK/x64_dll/BayerDec.dll`](https://github.com/Shining3D/EinScan-SDK/blob/master/SDK/x64_dll/BayerDec.dll), ... ) file.

Please send [me](mailto:cto@tienipia.com) a original zip which is not containing git-lfs pointer file but banaries.

Best regards.
James Choi.

**Comment by Nassiel** [comment]
Hi,

O also even try to speak with them via Skype without any answer. Our company bought your product but without this, it's completely useless.

Best Regards.

**Comment by Tienipia** [comment]
to. @Nassiel

Hello there, can you notify me the model of your 3D Scanner? I can't help you.
I'd tried to recover fragements of above mis-downloaded SDK files, finally I success with EinScan-Pro or EinScan-Pro Plus.

But recovered one is not matured(does not work with HD prime pack  & Color Pack), but works..

**Comment by Shining3D** [comment]
@Tienipia @Nassiel  Sorry for the inconvenience. We have already bought the data package. You may be able to clone the sdk, please try again.

**Comment by Tienipia** [comment]
@Shining3D why not support HD Prime pack for EinScan-Pro Plus? I want to use scanner with pack. please support additional SDK for dealing pack.

**Comment by Shining3D** [comment]
@Tienipia Thanks for suggestion. We haven't make the development plan to release sdk for HD Prime. We will notify you when we are ready to do that.

**Comment by Nassiel** [comment]
> to. @Nassiel
> 
> Hello there, can you notify me the model of your 3D Scanner? I can help you.
> I'd tried to recover fragements of above mis-downloaded SDK files, finally I success with EinScan-Pro or EinScan-Pro Plus.
> 
> But recovered one is not matured(does not work with HD prime pack & Color Pack), but works..

We are using the EinScan-SP. And I also success on downloading them.

Thanks @Shining3D.
